spring.application.name=finsentry-ai

spring.datasource.url=jdbc:postgresql://localhost:5432/finsentry
spring.datasource.username=finsentry
spring.datasource.password=finsentry
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver


spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.ai.vectorstore.pgvector.initialize-schema=true