spring.application.name=finsentry-ai

spring.datasource.url=jdbc:postgresql://localhost:5432/finsentry
spring.datasource.username=finsentry
spring.datasource.password=finsentry
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver


spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.ai.vectorstore.pgvector.initialize-schema=true