spring.application.name=finsentry-ai

spring.datasource.url=jdbc:postgresql://localhost:5432/finsentry
spring.datasource.username=finsentry
spring.datasource.password=finsentry
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver


spring.ai.openai.api-key=
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.ai.vectorstore.pgvector.initialize-schema=true
